// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your ViewModel apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await ViewModel.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBrYbbW3Y7Yp5sXohoLBYE2AEh113SX6Y',
    appId: '1:112018332653:web:95eaaaeab6288dbf79e5e4',
    messagingSenderId: '112018332653',
    projectId: 'fyptutor-0468',
    authDomain: 'fyptutor-0468.firebaseapp.com',
    storageBucket: 'fyptutor-0468.firebasestorage.app',
    measurementId: 'G-LKPQRKL2DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb4UBkJzHpuxTZeGG3BqaciSR9ytxipek',
    appId: '1:112018332653:android:3382a05dbd5fb81f79e5e4',
    messagingSenderId: '112018332653',
    projectId: 'fyptutor-0468',
    storageBucket: 'fyptutor-0468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqILvaumcTgSPRxbdoDrOHgPTe63hTr8',
    appId: '1:112018332653:ios:ca92c87b62a6ed4979e5e4',
    messagingSenderId: '112018332653',
    projectId: 'fyptutor-0468',
    storageBucket: 'fyptutor-0468.firebasestorage.app',
    iosBundleId: 'com.example.fypTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWqILvaumcTgSPRxbdoDrOHgPTe63hTr8',
    appId: '1:112018332653:ios:ca92c87b62a6ed4979e5e4',
    messagingSenderId: '112018332653',
    projectId: 'fyptutor-0468',
    storageBucket: 'fyptutor-0468.firebasestorage.app',
    iosBundleId: 'com.example.fypTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBrYbbW3Y7Yp5sXohoLBYE2AEh113SX6Y',
    appId: '1:112018332653:web:bbc285d1be446d5179e5e4',
    messagingSenderId: '112018332653',
    projectId: 'fyptutor-0468',
    authDomain: 'fyptutor-0468.firebaseapp.com',
    storageBucket: 'fyptutor-0468.firebasestorage.app',
    measurementId: 'G-5T7MDRF8RW',
  );
}
